# Generated by Django 3.2.8 on 2022-11-04 06:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_user', '0003_alter_account_managers'),
        ('api_course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=50)),
                ('course_title', models.CharField(default='', max_length=50)),
                ('last_learn_date', models.DateTimeField(default=django.utils.timezone.now, max_length=50)),
                ('learn_completed_date', models.DateTimeField(blank=True, null=True, max_length=50)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_course', to='api_course.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_course', to='api_user.user')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'process_course',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProcessLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('LOCK', 'LOCK'), ('OPEN', 'OPEN'), ('IN_PROGRESS', 'IN_PROGRESS'), ('TESTING', 'TESTING'), ('COMPLETED', 'COMPLETED')], default='LOCK', max_length=50)),
                ('lesson_title', models.CharField(default='', max_length=50)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lesson', to='api_course.attachment')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lesson', to='api_course.lesson')),
                ('previous_process_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_process.processlesson')),
                ('process_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_lesson', to='api_process.processcourse')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'process_lesson',
                'ordering': ('-created_at',),
            },
        ),
    ]
