version: '3.8'

services:

  app:
#    build: .
    ports:
      - 8000:8000
    image: bangpham2325/bangtestnginx2:latest
    container_name: django_container3
    restart: always
    env_file:
      - ./docker.env
    command: bash -c "python3 manage.py collectstatic --noinput && python3 manage.py migrate --noinput && gunicorn core.wsgi -b 0.0.0.0:8000"


  frontend:
    restart: always
#    build:
#      context: ./src/frontend
#      dockerfile: Dockerfile
    container_name: frontend2
    image: bangpham2325/frontend_image2
    depends_on:
      - app
#    volumes:
#      - ./src/frontend/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
