version: '3.8'

services:

  app:
    build: .
    # volumes:
    #   - .:/django/
    ports:
      - 5555:8000
    image: app:django
    container_name: django_container1
    restart: always
    env_file:
      - ./docker.env
  #   command: python manage.py runserver 0.0.0.0:8000
  #   depends_on:
  #     - db 
  # db:
  #   image: mysql:5.7
  #   ports:
  #     - "3307:3306"
  #   environment:
  #     MYSQL_DATABASE: 'django-app-db'
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  #   volumes:
  #     - ./data/mysql/db:/var/lib/mysql