# Generated by Django 3.2.8 on 2022-10-23 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_topic', '0001_initial'),
        ('api_user', '0002_init_account_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField()),
                ('background', models.FileField(blank=True, null=True, upload_to='course/')),
                ('cost', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('DEACTIVATE', 'DEACTIVATE')], default='DRAFT', max_length=50)),
                ('certificate_frame', models.TextField()),
                ('topics', models.ManyToManyField(blank=True, null=True, related_name='courses', to='api_topic.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api_user.user')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ('-created_at',),
            },
        ),
    ]
