# Generated by Django 3.2.8 on 2022-11-27 09:21

import api_course.models.course
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_alter_user_avatar'),
        ('api_course', '0002_auto_20221028_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_frame',
            field=models.FileField(blank=True, null=True, upload_to=api_course.models.course.upload_path_certificate),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='api_course.lesson')),
                ('parent_discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_discussions', to='api_course.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='api_user.user')),
            ],
            options={
                'db_table': 'discussions',
                'ordering': ('-created_at',),
            },
        ),
    ]
