# Generated by Django 3.2.8 on 2022-11-27 09:21

import api_course.models.course
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_alter_user_avatar'),
        ('api_course', '0002_auto_20221028_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='course',
            name='certificate_frame',
            field=models.FileField(blank=True, null=True, upload_to=api_course.models.course.upload_path_certificate),
        ),
    ]
