# Generated by Django 3.2.8 on 2022-12-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_course', '0003_auto_20221123_1855'),
        ('api_course', '0003_auto_20221127_1621'),
    ]

    operations = [
    ]
