export enum ActionTypes {
  // Authentication
  GET_TOKEN_INFO = 'GET_TOKEN_INFO',
  SET_TOKEN_INFO = 'SET_TOKEN_INFO',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',

  // Course
  FETCH_COURSES = 'FETCH_COURSES',
  FETCH_COURSE_DETAIL = 'FETCH_COURSE_DETAIL',
  CREATE_COURSE = 'CREATE_COURSE',
  UPDATE_COURSE_INFO = 'UPDATE_COURSE_INFO',
  DELETE_COURSE = 'DELETE_COURSE',

  // Topic
  FETCH_TOPICS = 'FETCH_TOPICS',
  ADD_TOPIC = 'ADD_TOPIC',
  UPDATE_TOPIC = 'UPDATE_TOPIC',
  DELETE_TOPIC = 'DELETE_TOPIC',

  // User
  GET_USER_INFO = 'GET_USER_INFO',

  //Chapter
  FETCH_CHAPTERS = 'FETCH_CHAPTERS',
  CREATE_CHAPTER = 'CREATE_CHAPTER',
  UPDATE_CHAPTER = 'UPDATE_CHAPTER',
  REMOVE_CHAPTER = 'REMOVE_CHAPTER',

  //Lesson
  FETCH_LESSON_DETAIL = 'FETCH_LESSON_DETAIL',
}
