export enum ActionTypes {
  // Authentication
  GET_TOKEN_INFO = 'GET_TOKEN_INFO',
  SET_TOKEN_INFO = 'SET_TOKEN_INFO',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',

  // Course
  FETCH_COURSES = 'FETCH_COURSES',
  FETCH_COURSE_DETAIL = 'FETCH_COURSE_DETAIL',
  CREATE_COURSE = 'CREATE_COURSE',
  UPDATE_COURSE_INFO = 'UPDATE_COURSE_INFO',

  // Topic
  FETCH_TOPICS = 'FETCH_TOPICS',

  // User
  GET_USER_INFO = 'GET_USER_INFO'
}
