export enum ActionTypes {
  // Authentication
  GET_TOKEN_INFO = 'GET_TOKEN_INFO',
  SET_TOKEN_INFO = 'SET_TOKEN_INFO',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',

  // Course
  FETCH_COURSES = 'FETCH_COURSES',
  FETCH_COURSE_DETAIL = 'FETCH_COURSE_DETAIL',
  CREATE_COURSE = 'CREATE_COURSE',
  UPDATE_COURSE_INFO = 'UPDATE_COURSE_INFO',
  DELETE_COURSE = 'DELETE_COURSE',

  // LESSON
  CREATE_LESSON = 'CREATE_LESSON',
  UPDATE_LESSON = 'UPDATE_LESSON',
  DELETE_LESSON = 'DELETE_LESSON',
  FETCH_LESSON_DETAIL = 'FETCH_LESSON_DETAIL',

  // TOPIC
  FETCH_TOPICS = 'FETCH_TOPICS',
  ADD_TOPIC = 'ADD_TOPIC',
  UPDATE_TOPIC = 'UPDATE_TOPIC',
  DELETE_TOPIC = 'DELETE_TOPIC',

  // USER
  GET_USER_INFO = 'GET_USER_INFO',

  // CHAPTER
  FETCH_CHAPTERS = 'FETCH_CHAPTERS',
  CREATE_CHAPTER = 'CREATE_CHAPTER',
  UPDATE_CHAPTER = 'UPDATE_CHAPTER',
  REMOVE_CHAPTER = 'REMOVE_CHAPTER',

  // COURSE PROCESS
  FETCH_COURSES_PROCESS = 'FETCH_COURSES_PROCESS',
  FETCH_USER_COURSES_PROCESS = 'FETCH_USER_COURSES_PROCESS',
  FETCH_COURSE_PROCESS_DETAIL = 'FETCH_COURSE_PROCESS_DETAIL',
  CREATE_COURSE_PROCESS = 'CREATE_COURSE_PROCESS',

  // LESSON PROCESS
  FETCH_LESSON_PROCESS_DETAIL = 'FETCH_LESSON_PROCESS_DETAIL',
  UPDATE_LESSON_PROCESS = 'UPDATE_LESSON_PROCESS',

  //DISCUSSION
  FETCH_COMMENTS = "FETCH_COMMENTS",
  CREATE_COMMENT= "CREATE_COMMENT",
  REPLY_COMMENT = "REPLY_COMMENT",
  UPDATE_COMMENT = "UPDATE_COMMENT",
  REMOVE_COMMENT = "REMOVE_COMMENT", 
}
