# Generated by Django 3.2.8 on 2022-10-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_init_account_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
    ]
